spring.main.web-application-type=none

spring.datasource.url=<url>
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.ai.huggingface.chat.api-key=key
spring.ai.huggingface.chat.url=url